codecov:
  require_ci_to_pass: true

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
  branches:
    - develop

coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 5%
        if_ci_failed: error


ignore:
  - 'lib/models/result.freezed.dart'
  - 'lib/models/**/*.freezed.dart'
  - 'lib/models/*/*.freezed.dart'
  - 'lib/models/*/*.g.dart'
  - 'lib/gen/*.gen.dart'
  - 'lib/firebase_options.dart'
  - 'lib/util/logger.dart'