include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    leading_newlines_in_multiline_strings: ignore
    require_trailing_commas: ignore
    use_build_context_synchronously: ignore

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    sort_pub_dependencies: false
    non_constant_identifier_names: false