coverage:
  status:
    project:
      default:
        target: 100%
        threshold: 0%
    patch:
      default:
        target: 100%
        threshold: 0%


ignore:
  - 'lib/models/result.freezed.dart'
  - 'lib/models/**/*.freezed.dart'
  - 'lib/models/*/*.freezed.dart'
  - 'lib/models/*/*.g.dart'
  - 'lib/gen/*.gen.dart'
  - 'lib/firebase_options.dart'
  - 'lib/util/logger.dart'