codecov:
  require_ci_to_pass: true

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: false
  branches:
    - develop

coverage:
  range: 10..100
  round: down
  precision: 2
  status:
    project:
      default:
        target: 10%
        threshold: 0%
    patch:
      target: 10%
      threshold: 0%


ignore:
  - 'lib/models/result.freezed.dart'
  - 'lib/models/**/*.freezed.dart'
  - 'lib/models/*/*.freezed.dart'
  - 'lib/models/*/*.g.dart'
  - 'lib/gen/*.gen.dart'
  - 'lib/firebase_options.dart'
  - 'lib/util/logger.dart'