coverage:
  status:
    project:
      default:
        target: 10%
        threshold: 0%


ignore:
  - 'lib/*.freezed.dart'
  - 'lib/*.g.dart'
  - 'lib/gen/*.gen.dart'
  - 'lib/firebase_options.dart'
  - 'lib/util/logger.dart'
  - 'lib/provider/login/*.dart'
  - 'lib/provider/global_providers.dart'
  - 'lib/provider/logout.dart'
  - 'lib/provider/profile_images.dart'
  - 'lib/provider/share_db.dart'
  - 'lib/provider/tool_tip_check.dart'
  - 'lib/initial_settings.dart'
  - 'lib/routes.dart'
  - 'lib/main.dart'
  - 'lib/di/set_up_get_it.dart'
  - 'lib/const/*.dart'