name: ac_project_app
description: 비사이드 12기 먼데이 로켓팀 프로젝트

publish_to: 'none'

version: 1.0.8+8

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:

  ## Network
  dio: ^4.0.6
  json_annotation: ^4.6.0
  http: ^0.13.5

  ## Architecture
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5

  ## login
  sign_in_with_apple: ^4.1.0
  google_sign_in: ^5.4.1
  firebase_auth: ^4.0.2

  ## Utils
  very_good_analysis: ^3.0.1
  metadata_fetch: ^0.4.1
  permission_handler: ^10.0.2
  flutter_dotenv: ^5.0.2
  logger: ^1.1.0
  path_provider: ^2.0.11
  intl: ^0.17.0
  path: ^1.8.2
  fluttertoast: ^8.1.1

  ## SVG
  flutter_svg: ^1.1.6

  ## for Database
  sqflite: ^2.1.0+1

  ## for Test Functions
  geolocator: ^9.0.1
  flutter_signin_button: ^2.0.0
  freezed_annotation: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # for model class
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  analyzer: ^5.1.0
  freezed: ^2.1.1

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/images/login/
    - assets/images/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard/Pretendard-Thin.otf
          weight: 200
        - asset: assets/fonts/Pretendard/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard/Pretendard-Bold.otf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
