name: ac_project_app
description: 비사이드 12기 먼데이 로켓팀 프로젝트

publish_to: 'none'

version: 1.0.2+2

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:

  ## Network
  retrofit: ^3.0.1+1
  dio: ^4.0.6
  json_annotation: ^4.6.0

  ## Architecture
  flutter_bloc: ^8.1.1

  ## login
  sign_in_with_apple: ^4.1.0
  google_sign_in: ^5.4.1
  kakao_flutter_sdk_user: ^1.2.1
  firebase_auth: ^3.9.0

  ## Utils
  very_good_analysis: ^3.0.1
  metadata_fetch: ^0.4.1
  permission_handler: ^10.0.2
  flutter_dotenv: ^5.0.2
  logger: ^1.1.0
  path_provider: ^2.0.11
  flutter_background_service: ^2.4.3

  ## for Test Functions
  geolocator: ^9.0.1
  flutter_signin_button: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  retrofit_generator: '>=4.0.0 <5.0.0'

  # for model class
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  freezed: ^1.1.1


flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/images/login/3.0x/
    - assets/images/login/2.0x/
    - assets/images/login/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard/Pretendard-Thin.otf
          weight: 200
        - asset: assets/fonts/Pretendard/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard/Pretendard-Bold.otf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
