name: ac_project_app
description: 링크풀 - 체계적인 링크 관리의 시작

publish_to: 'none'

version: 1.0.70+70

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:

  ## Network
  dio: ^5.4.1
  json_annotation: ^4.8.0
  http: ^1.0.0
  cached_network_image: ^3.3.1

  ## Architecture
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  get_it: ^7.6.0

  ## login
  sign_in_with_apple: ^7.0.1
  google_sign_in: ^6.2.2
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  firebase_database: ^11.3.6
  firebase_crashlytics: ^4.3.6

  kakao_flutter_sdk_user: ^1.6.1
  flutter_dotenv: ^5.0.2
  flutter_naver_login: ^2.1.1

  firebase_auth_mocks: ^0.14.1

  # app link
  app_links: ^6.3.2

  ## UI Sizer
  flutter_screenutil: ^5.9.0

  ## kakao_share
  kakao_flutter_sdk_share: ^1.6.1

  ## Utils
  metadata_fetch:
    git:
      url: https://github.com/boring-km/metadata_fetch.git

  permission_handler: ^12.0.0+1
  logger: ^1.3.0
  path_provider: ^2.1.5
  intl: ^0.18.1
  path: ^1.8.3
  oktoast:
  share_plus: ^7.2.2
  flutter_keyboard_visibility: ^6.0.0
  extended_text: ^15.0.0
  carousel_slider: ^5.0.0
  lottie:
  flutter_slidable: ^3.1.1
  firebase_storage:

  ## lint
  very_good_analysis: ^4.0.0+1

  ## SVG
  flutter_svg: ^2.0.6

  ## for Storage
  sqflite: ^2.4.1
  shared_preferences: ^2.1.0

  ## for Test Functions
  flutter_signin_button: ^2.0.0
  freezed_annotation: ^2.2.0

  ## Web
  url_launcher: ^6.3.1
  url_launcher_android: ^6.3.14
  url_launcher_ios: ^6.3.1

  # for mock test
  mockito: ^5.4.4
  build_runner: ^2.4.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  bloc_test: ^9.1.2

  # for model class
  json_serializable: ^6.8.0
  analyzer: ^6.7.0
  freezed: ^2.5.7
  flutter_oss_licenses: ^3.0.2

flutter:

  uses-material-design: true

  assets:
    - assets/images/profile/
    - assets/images/login/
    - assets/images/
    - assets/tutorials/
    - .env
    - assets/animations/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard/Pretendard-Thin.otf
          weight: 200
        - asset: assets/fonts/Pretendard/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard/Pretendard-Bold.otf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700

