name: ac_project_app
description: 링크풀 - 체계적인 링크 관리의 시작

publish_to: 'none'

version: 1.0.44+44

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:

  ## Network
  dio: ^5.2.0+1
  json_annotation: ^4.8.0
  http: ^0.13.6
  cached_network_image: ^3.2.3

  ## Architecture
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.0

  ## login
  sign_in_with_apple: ^4.3.0
  google_sign_in: ^6.1.4
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2
  firebase_dynamic_links: ^5.3.2

  kakao_flutter_sdk_user: ^1.4.3
  flutter_dotenv: ^5.0.2
  flutter_naver_login: ^1.8.0

  firebase_auth_mocks: ^0.11.0

  ## UI Sizer
  flutter_screenutil: ^5.7.0

  ## kakao_share
  kakao_flutter_sdk_share: ^1.4.3

  ## Utils
  metadata_fetch: ^0.4.1
  permission_handler: ^10.2.0
  logger: ^1.3.0
  path_provider: ^2.0.15
  intl: ^0.18.1
  path: ^1.8.3
  oktoast:
  share_plus: ^6.3.1
  flutter_keyboard_visibility: ^5.4.1
  extended_text: ^11.0.1
  carousel_slider: ^4.2.1
  lottie:
  flutter_slidable: ^2.0.0

  ## lint
  very_good_analysis: ^4.0.0+1

  ## SVG
  flutter_svg: ^2.0.6

  ## for Storage
  sqflite: ^2.2.6
  shared_preferences: ^2.1.0

  ## for Test Functions
  flutter_signin_button: ^2.0.0
  freezed_annotation: ^2.2.0

  ## Web
  url_launcher: ^6.1.10

  # for mock test
  mockito: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  bloc_test: ^9.1.2

  # for model class
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  analyzer: ^5.10.0
  freezed: ^2.3.2

flutter:

  uses-material-design: true

  assets:
    - assets/images/profile/
    - assets/images/login/
    - assets/images/
    - assets/tutorials/
    - .env
    - assets/animations/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard/Pretendard-Thin.otf
          weight: 200
        - asset: assets/fonts/Pretendard/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard/Pretendard-Bold.otf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
