name: ac_project_app
description: 비사이드 12기 먼데이 로켓팀 프로젝트

publish_to: 'none'

version: 1.0.2+2

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  flutter_bloc: ^8.1.1

  very_good_analysis: ^3.0.1
  retrofit: ^3.0.1+1
  dio: ^4.0.6
  json_annotation: ^4.6.0
  logger:
  geolocator: ^9.0.1
  permission_handler:
  flutter_dotenv: ^5.0.2
  sign_in_with_apple: ^4.1.0
  google_sign_in: ^5.4.1
  kakao_flutter_sdk_user: ^1.2.1
  path_provider:
  flutter_background_service:

  firebase_auth: ^3.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  retrofit_generator: '>=4.0.0 <5.0.0'

  # for model class
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  freezed: ^1.1.1


flutter:

  uses-material-design: true

  assets:
    - .env
    - images/