// Mocks generated by Mockito 5.4.6 from annotations
// in ac_project_app/test/cubits/local_folders_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:ac_project_app/models/local/local_folder.dart' as _i4;
import 'package:ac_project_app/provider/local/local_folder_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [LocalFolderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalFolderRepository extends _i1.Mock
    implements _i2.LocalFolderRepository {
  MockLocalFolderRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.LocalFolder>> getAllFolders() => (super.noSuchMethod(
        Invocation.method(
          #getAllFolders,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.LocalFolder>>.value(<_i4.LocalFolder>[]),
      ) as _i3.Future<List<_i4.LocalFolder>>);

  @override
  _i3.Future<List<_i4.LocalFolder>> getClassifiedFolders() =>
      (super.noSuchMethod(
        Invocation.method(
          #getClassifiedFolders,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.LocalFolder>>.value(<_i4.LocalFolder>[]),
      ) as _i3.Future<List<_i4.LocalFolder>>);

  @override
  _i3.Future<_i4.LocalFolder?> getUnclassifiedFolder() => (super.noSuchMethod(
        Invocation.method(
          #getUnclassifiedFolder,
          [],
        ),
        returnValue: _i3.Future<_i4.LocalFolder?>.value(),
      ) as _i3.Future<_i4.LocalFolder?>);

  @override
  _i3.Future<_i4.LocalFolder?> getFolderById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getFolderById,
          [id],
        ),
        returnValue: _i3.Future<_i4.LocalFolder?>.value(),
      ) as _i3.Future<_i4.LocalFolder?>);

  @override
  _i3.Future<int> createFolder(_i4.LocalFolder? folder) => (super.noSuchMethod(
        Invocation.method(
          #createFolder,
          [folder],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> updateFolder(_i4.LocalFolder? folder) => (super.noSuchMethod(
        Invocation.method(
          #updateFolder,
          [folder],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> deleteFolder(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteFolder,
          [id],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<_i4.LocalFolder>> searchFolders(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchFolders,
          [query],
        ),
        returnValue:
            _i3.Future<List<_i4.LocalFolder>>.value(<_i4.LocalFolder>[]),
      ) as _i3.Future<List<_i4.LocalFolder>>);

  @override
  _i3.Future<int> updateThumbnail(
    int? folderId,
    String? thumbnail,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateThumbnail,
          [
            folderId,
            thumbnail,
          ],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> getFolderCount() => (super.noSuchMethod(
        Invocation.method(
          #getFolderCount,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
}
