// Mocks generated by Mockito 5.4.6 from annotations
// in ac_project_app/test/cubits/local_search_links_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:ac_project_app/models/local/local_link.dart' as _i4;
import 'package:ac_project_app/provider/local/local_link_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [LocalLinkRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalLinkRepository extends _i1.Mock
    implements _i2.LocalLinkRepository {
  MockLocalLinkRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.LocalLink>> getAllLinks({
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllLinks,
          [],
          {
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i3.Future<List<_i4.LocalLink>>.value(<_i4.LocalLink>[]),
      ) as _i3.Future<List<_i4.LocalLink>>);

  @override
  _i3.Future<List<_i4.LocalLink>> getLinksByFolderId(
    int? folderId, {
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLinksByFolderId,
          [folderId],
          {
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i3.Future<List<_i4.LocalLink>>.value(<_i4.LocalLink>[]),
      ) as _i3.Future<List<_i4.LocalLink>>);

  @override
  _i3.Future<_i4.LocalLink?> getLinkById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getLinkById,
          [id],
        ),
        returnValue: _i3.Future<_i4.LocalLink?>.value(),
      ) as _i3.Future<_i4.LocalLink?>);

  @override
  _i3.Future<int> createLink(_i4.LocalLink? link) => (super.noSuchMethod(
        Invocation.method(
          #createLink,
          [link],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> updateLink(_i4.LocalLink? link) => (super.noSuchMethod(
        Invocation.method(
          #updateLink,
          [link],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> deleteLink(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteLink,
          [id],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> moveLink(
    int? linkId,
    int? newFolderId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #moveLink,
          [
            linkId,
            newFolderId,
          ],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> moveLinks(
    List<int>? linkIds,
    int? newFolderId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #moveLinks,
          [
            linkIds,
            newFolderId,
          ],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<_i4.LocalLink>> searchLinks(
    String? query, {
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchLinks,
          [query],
          {#limit: limit},
        ),
        returnValue: _i3.Future<List<_i4.LocalLink>>.value(<_i4.LocalLink>[]),
      ) as _i3.Future<List<_i4.LocalLink>>);

  @override
  _i3.Future<int> getLinkCountByFolderId(int? folderId) => (super.noSuchMethod(
        Invocation.method(
          #getLinkCountByFolderId,
          [folderId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> getTotalLinkCount() => (super.noSuchMethod(
        Invocation.method(
          #getTotalLinkCount,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<bool> isUrlExists(String? url) => (super.noSuchMethod(
        Invocation.method(
          #isUrlExists,
          [url],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<_i4.LocalLink?> getLinkByUrl(String? url) => (super.noSuchMethod(
        Invocation.method(
          #getLinkByUrl,
          [url],
        ),
        returnValue: _i3.Future<_i4.LocalLink?>.value(),
      ) as _i3.Future<_i4.LocalLink?>);
}
