default_platform(:ios)
APPLICATION_ID = ENV["APPLICATION_ID"]
BUNDLE_IDENTIFIER = ENV["BUNDLE_IDENTIFIER"]
EXTENSION_IDENTIFIER = ENV["EXTENSION_IDENTIFIER"]

platform :ios do
  lane :closed_beta do
    setup_ci

    match(
      type: 'appstore',
      app_identifier: ["#{BUNDLE_IDENTIFIER}", "#{EXTENSION_IDENTIFIER}"],
      git_basic_authorization: Base64.strict_encode64(ENV["GIT_AUTHORIZATION"]),
      readonly: true,
      verbose: true
    )

    gym(
      configuration: "Release",
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store-connect",
      export_options: {
        teamID: "T583WJWNAK",
        provisioningProfiles: {
          "com.mr.acProjectApp" => "match AppStore com.mr.acProjectApp",
          "com.mr.acProjectApp.Extension" => "match AppStore com.mr.acProjectApp.Extension"
        }
      }
    )

    pilot(
      apple_id: "#{APPLICATION_ID}",
      app_identifier: "#{BUNDLE_IDENTIFIER}",
      skip_waiting_for_build_processing: true,
      skip_submission: true,
      distribute_external: false,
      notify_external_testers: false,
      ipa: "./Runner.ipa"
    )
  end
end
