# Replace evverything in Fastfile with below code
default_platform(:ios)
APPLICATION_ID = ENV["APPLICATION_ID"]
BUNDLE_IDENTIFIER = ENV["BUNDLE_IDENTIFIER"]
EXTENSION_IDENTIFIER = ENV["EXTENSION_IDENTIFIER"]
TEMP_KEYCHAIN_USER = ENV["TEMP_KEYCHAIN_USER"]
TEMP_KEYCHAIN_PASSWORD = ENV["TEMP_KEYCHAIN_PASSWORD"]
def delete_temp_keychain(name)
  delete_keychain(
    name: name
  ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
end
def create_temp_keychain(name, password)
  create_keychain(
    name: name,
    password: password,
    unlock: true,
    timeout: 0,
    lock_when_sleeps: false
  )
end
def ensure_temp_keychain(name, password)
  delete_temp_keychain(name)
  create_temp_keychain(name, password)
end
platform :ios do
  lane :closed_beta do
    keychain_name = TEMP_KEYCHAIN_USER
    keychain_password = TEMP_KEYCHAIN_PASSWORD
    ensure_temp_keychain(keychain_name, keychain_password)
    match(
      type: 'appstore',
      app_identifier: ["#{BUNDLE_IDENTIFIER}", "#{EXTENSION_IDENTIFIER}"],
      git_basic_authorization: Base64.strict_encode64(ENV["GIT_AUTHORIZATION"]),
      keychain_name: keychain_name,
      keychain_password: keychain_password,
      verbose: true
    )
    gym(
      configuration: "Release",
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      export_options: {
        teamID: "T583WJWNAK",
        provisioningProfiles: {
          "com.mr.acProjectApp" => "match AppStore com.mr.acProjectApp",
          "com.mr.acProjectApp.Extension" => "match AppStore com.mr.acProjectApp.Extension"
        }
      }
    )
    pilot(
      apple_id: "#{APPLICATION_ID}",
      app_identifier: "#{BUNDLE_IDENTIFIER}",
      skip_waiting_for_build_processing: true,
      skip_submission: true,
      distribute_external: false,
      notify_external_testers: false,
      ipa: "./Runner.ipa"
    )
    delete_temp_keychain(keychain_name)
  end
end