// Mocks generated by Mockito 5.4.6 from annotations
// in ac_project_app/test/ui/widget/folder/show_create_folder_sheet_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:ac_project_app/cubits/folders/create_folder_result.dart' as _i8;
import 'package:ac_project_app/cubits/folders/folders_state.dart' as _i2;
import 'package:ac_project_app/cubits/folders/local_folders_cubit.dart' as _i6;
import 'package:ac_project_app/models/folder/folder.dart' as _i7;
import 'package:ac_project_app/models/local/local_folder.dart' as _i5;
import 'package:ac_project_app/provider/local/local_folder_repository.dart'
    as _i3;
import 'package:flutter_bloc/flutter_bloc.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFoldersState_0 extends _i1.SmartFake implements _i2.FoldersState {
  _FakeFoldersState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LocalFolderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalFolderRepository extends _i1.Mock
    implements _i3.LocalFolderRepository {
  MockLocalFolderRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.LocalFolder>> getAllFolders() => (super.noSuchMethod(
        Invocation.method(
          #getAllFolders,
          [],
        ),
        returnValue:
            _i4.Future<List<_i5.LocalFolder>>.value(<_i5.LocalFolder>[]),
      ) as _i4.Future<List<_i5.LocalFolder>>);

  @override
  _i4.Future<List<_i5.LocalFolder>> getClassifiedFolders() =>
      (super.noSuchMethod(
        Invocation.method(
          #getClassifiedFolders,
          [],
        ),
        returnValue:
            _i4.Future<List<_i5.LocalFolder>>.value(<_i5.LocalFolder>[]),
      ) as _i4.Future<List<_i5.LocalFolder>>);

  @override
  _i4.Future<_i5.LocalFolder?> getUnclassifiedFolder() => (super.noSuchMethod(
        Invocation.method(
          #getUnclassifiedFolder,
          [],
        ),
        returnValue: _i4.Future<_i5.LocalFolder?>.value(),
      ) as _i4.Future<_i5.LocalFolder?>);

  @override
  _i4.Future<_i5.LocalFolder?> getFolderById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getFolderById,
          [id],
        ),
        returnValue: _i4.Future<_i5.LocalFolder?>.value(),
      ) as _i4.Future<_i5.LocalFolder?>);

  @override
  _i4.Future<int> createFolder(_i5.LocalFolder? folder) => (super.noSuchMethod(
        Invocation.method(
          #createFolder,
          [folder],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<bool> isSiblingNameTaken(
    int? parentId,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isSiblingNameTaken,
          [
            parentId,
            name,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<int> updateFolder(_i5.LocalFolder? folder) => (super.noSuchMethod(
        Invocation.method(
          #updateFolder,
          [folder],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> deleteFolder(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteFolder,
          [id],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<List<_i5.LocalFolder>> searchFolders(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchFolders,
          [query],
        ),
        returnValue:
            _i4.Future<List<_i5.LocalFolder>>.value(<_i5.LocalFolder>[]),
      ) as _i4.Future<List<_i5.LocalFolder>>);

  @override
  _i4.Future<int> updateThumbnail(
    int? folderId,
    String? thumbnail,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateThumbnail,
          [
            folderId,
            thumbnail,
          ],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> getFolderCount() => (super.noSuchMethod(
        Invocation.method(
          #getFolderCount,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<List<_i5.LocalFolder>> getRootFolders() => (super.noSuchMethod(
        Invocation.method(
          #getRootFolders,
          [],
        ),
        returnValue:
            _i4.Future<List<_i5.LocalFolder>>.value(<_i5.LocalFolder>[]),
      ) as _i4.Future<List<_i5.LocalFolder>>);

  @override
  _i4.Future<List<_i5.LocalFolder>> getChildFolders(int? parentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChildFolders,
          [parentId],
        ),
        returnValue:
            _i4.Future<List<_i5.LocalFolder>>.value(<_i5.LocalFolder>[]),
      ) as _i4.Future<List<_i5.LocalFolder>>);

  @override
  _i4.Future<List<_i5.LocalFolder>> getAllDescendants(int? folderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllDescendants,
          [folderId],
        ),
        returnValue:
            _i4.Future<List<_i5.LocalFolder>>.value(<_i5.LocalFolder>[]),
      ) as _i4.Future<List<_i5.LocalFolder>>);

  @override
  _i4.Future<List<_i5.LocalFolder>> getBreadcrumb(int? folderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBreadcrumb,
          [folderId],
        ),
        returnValue:
            _i4.Future<List<_i5.LocalFolder>>.value(<_i5.LocalFolder>[]),
      ) as _i4.Future<List<_i5.LocalFolder>>);

  @override
  _i4.Future<Map<int, int>> getRecursiveLinkCounts() => (super.noSuchMethod(
        Invocation.method(
          #getRecursiveLinkCounts,
          [],
        ),
        returnValue: _i4.Future<Map<int, int>>.value(<int, int>{}),
      ) as _i4.Future<Map<int, int>>);

  @override
  _i4.Future<bool> moveFolder(
    int? folderId,
    int? newParentId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #moveFolder,
          [
            folderId,
            newParentId,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}

/// A class which mocks [LocalFoldersCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalFoldersCubit extends _i1.Mock implements _i6.LocalFoldersCubit {
  MockLocalFoldersCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i7.Folder> get folders => (super.noSuchMethod(
        Invocation.getter(#folders),
        returnValue: <_i7.Folder>[],
      ) as List<_i7.Folder>);

  @override
  set folders(List<_i7.Folder>? value) => super.noSuchMethod(
        Invocation.setter(
          #folders,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.FoldersState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeFoldersState_0(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.FoldersState);

  @override
  _i4.Stream<_i2.FoldersState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i4.Stream<_i2.FoldersState>.empty(),
      ) as _i4.Stream<_i2.FoldersState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> getFolders({bool? isFirst}) => (super.noSuchMethod(
        Invocation.method(
          #getFolders,
          [],
          {#isFirst: isFirst},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  int getTotalLinksCount() => (super.noSuchMethod(
        Invocation.method(
          #getTotalLinksCount,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i4.Future<void> getFoldersWithoutUnclassified() => (super.noSuchMethod(
        Invocation.method(
          #getFoldersWithoutUnclassified,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> changeName(
    _i7.Folder? folder,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #changeName,
          [
            folder,
            name,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> delete(_i7.Folder? folder) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [folder],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<_i8.CreateFolderResult> createFolder(
    String? name, {
    int? parentId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createFolder,
          [name],
          {#parentId: parentId},
        ),
        returnValue: _i4.Future<_i8.CreateFolderResult>.value(
            _i9.dummyValue<_i8.CreateFolderResult>(
          this,
          Invocation.method(
            #createFolder,
            [name],
            {#parentId: parentId},
          ),
        )),
      ) as _i4.Future<_i8.CreateFolderResult>);

  @override
  _i4.Future<void> filter(String? name) => (super.noSuchMethod(
        Invocation.method(
          #filter,
          [name],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<int> getAddedLinksCount() => (super.noSuchMethod(
        Invocation.method(
          #getAddedLinksCount,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int?> getUnclassifiedFolderId() => (super.noSuchMethod(
        Invocation.method(
          #getUnclassifiedFolderId,
          [],
        ),
        returnValue: _i4.Future<int?>.value(),
      ) as _i4.Future<int?>);

  @override
  void emit(_i2.FoldersState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i10.Change<_i2.FoldersState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
