name: Measure Code Coverage
on:
  pull_request:
    branches:
      - develop
jobs:
  # internal test
  code-coverage:
    name: Flutter Test and Measure Code Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: '3.7.12'
      - name: Install packages
        run: flutter pub get
      - run: echo '${{ secrets.DOTENV }}' | base64 -d > .env
      - run: echo "${{ secrets.FIREBASE_OPTIONS }}" | base64 -d > ./lib/firebase_options.dart
      - name: run flutter test
        run: flutter test --coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
